services:
  postgres:
    image: postgres:17
    container_name: nest_template
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: